#====================================================
# bill测试环境配置
#====================================================

spring:
  application:
    name: bill
  # 默认时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  cloud:
    inetutils:
      default-ip-address: 127.0.0.1
  #spring redis
  redis:
    host: 127.0.0.1
    port: 6379
    password: redisl1
    timeout: 1000
    pool:
      # 连接池最大连接数（使用负值表示没有限制）
      max-active: 500
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: 1000
      # 连接池中的最大空闲连接
      max-idle: 100
      min-idle: 10
  #spring rabbitmq
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: rabbitadmin
    password: rabbit1
    # 开启发送确认
    publisher-confirms: true
    virtual-host: /
    listener:
      concurrency: 10
      max-concurrency: 15
      # 手动ack
      acknowledge-mode: manual
      prefetch: 1

# 微服务注册
eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:root@127.0.0.1:10000/eureka/
    healthcheck:
      enabled: true
  instance:
    hostname: ${spring.cloud.inetutils.default-ip-address}
    ip-address: ${spring.cloud.inetutils.default-ip-address}
    prefer-ip-address: true
    instance-id: ${spring.cloud.inetutils.default-ip-address}:${server.port}

# 停止服务
endpoints:
  shutdown:
    #开启shutdown端点
    enabled: true
    path: stop
management:
  security:
    #是否启用安全
    enabled: true
  port: 10003
  address: 127.0.0.1

server:
  port: 10003
  tomcat:
    uri-encoding: utf-8

#读写分离数据库
druid:
    type: com.alibaba.druid.pool.DruidDataSource
    master:
        name: mysql
        url: jdbc:mysql://127.0.0.1:3306/commerce?useUnicode=true&characterEncoding=UTF-8
        username: root
        password: sql123
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    slave:
        name: mysql
        url: jdbc:mysql://127.0.0.1:3306/commerce?useUnicode=true&characterEncoding=UTF-8
        username: root
        password: sql123
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20

#mybatis
mybatis:
  mapper-locations: classpath:mapper/*/*.xml
  type-aliases-package: com.bill.model.po
  #开启驼峰命名转换
  configuration:
      map-underscore-to-camel-case: true
      default-executor-type: batch

# mybatis分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

# swagger
swagger2:
    package: com.bill.controller
    enable: true

# 熔断
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          
# 日志配置dev
logback-logstash-tcp: localhost:9700
logback-application-path: applicationLog/
logback-performance-path: performanceLog/
logback-max-history: 30

          
