#====================================================
# bill测试环境配置
#====================================================

spring:
  # 默认时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  cache: 
    type: caffeine
    cache-names: getQueryProductVO
    caffeine:
      spec: maximumSize=1000,expireAfterAccess=600s
    
server:
  port: 10003
  tomcat:
    uri-encoding: utf-8    
    max-threads: 2000
    accept-count: 2000
    max-connections: 2000
    
# mybatis
mybatis:
  mapper-locations: classpath:mapper/*/*.xml
  #开启驼峰命名转换
  configuration:
      map-underscore-to-camel-case: true
      default-executor-type: batch
      default-statement-timeout: 30

# mybatis分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

# swagger
swagger2:
    package: com.bill.controller
    enable: true
    
# 熔断
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE    
    
ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 3000
  
url: 
  link: http://127.0.0.1:10003/
    
