#====================================================
# bill测试环境配置
#====================================================

spring:
  # 默认时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    
server:
  port: 10003
  tomcat:
    uri-encoding: utf-8    
    
# mybatis
mybatis:
  mapper-locations: classpath:mapper/*/*.xml
  type-aliases-package: com.bill.model.po
  #开启驼峰命名转换
  configuration:
      map-underscore-to-camel-case: true
      default-executor-type: batch

# mybatis分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

# swagger
swagger2:
    package: com.bill.controller
    enable: true
    
# 熔断
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE    
    
    
