spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    
server:
  port: 10002
  tomcat:
    uri-encoding: utf-8
    max-threads: 2000
    accept-count: 2000
    max-connections: 2000
    
# mybatis
mybatis:
  mapper-locations: classpath:mapper/*/*.xml
  type-aliases-package: com.member.model.po
  #开启驼峰命名转换
  configuration:
      map-underscore-to-camel-case: true
      default-statement-timeout: 30

# pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

# swagger
swagger2:
    package: com.member.controller
    
# redis
redis:
    ADDR: 127.0.0.1
    AUTH: redisl1
    PORT: 6379
    MAXACTIVE: -1
    MAXIDLE: 200
    MAXWAIT: 500
    TIMEOUT: 500
    TESTON_BORROW: true

# 熔断
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          
ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 3000

# token域
external-apex: localhost

# jwt密钥
login-secret: SIGNING_SECRET    

    
