#spring rabbitmq
spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: rabbitadmin
    password: rabbit1
    # 开启发送确认
    publisher-confirms: true
    virtual-host: /
    listener:
      concurrency: 10
      max-concurrency: 15
      # 手动ack
      acknowledge-mode: manual
      prefetch: 1
      
      
