#spring redis
spring:
  redis:
    host: 127.0.0.1
    port: 6379
    password: redisl1
    timeout: 1000
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 500
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 1000
        # 连接池中的最大空闲连接
        max-idle: 100
        min-idle: 10
      
      
      
