spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  
# 启动端口
server:
  port: 10001
  
zuul:
  host:
    socket-timeout-millis: 5000
    connect-timeout-millis: 3000
  
# 网关配置
#zuul:
#  # 忽略所有微服务
#  ignored-services: '*'
#  routes:
#    bill: /user/**

# 文件下载地址
upload-path: upload/

# jwt密钥
login-secret: SIGNING_SECRET      
